version: "3.3"
services:
  php74:
    build:
      context: docker/php-74
      dockerfile: dockerfile
    ports:
      - 8080:80
    working_dir: /app
    environment:
      - MYSQL_DATABASE=compets_management
      - MYSQL_USER=root
      - MYSQL_HOST=localhost
    volumes:
      - ./code:/app
    depends_on:
      - db

  composer:
    restart: "no"
    image: composer
    command: install
    working_dir: /app
    volumes:
      - ./code:/app

  db:
    image: mysql:5.7
    container_name: appsDB
    environment:
      - MYSQL_DATABASE=compets_management
      - MYSQL_USER=root
      - MYSQL_HOST=localhost
      - MYSQL_PASSWORD=admin
    restart: always
    ports:
      - "3306:3306"

  app:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8060:80"
    environment:
      PMA_HOST: db
